CC = gcc
CFLAGS = -g
SOURCES = $(wildcard *.c)
BINAIRES = $(patsubst %.c,%.o,${SOURCES})

all : ${BINAIRES}
	${CC} ${CFLAGS} -o main $^

main.o : chiffrage.h

chiffrage.o : chiffrage.h

clean :
	rm -f *.o